drop table KORISNICI cascade constraints; 
drop table APLIKACIJE cascade constraints; 
drop table LOKACIJE cascade constraints;
drop table MEDIA cascade constraints;
drop sequence APLIKACIJE_ID_SEQ;
drop sequence KORISNICI_ID_SEQ;
drop sequence LOKACIJE_ID_SEQ;
drop sequence MEDIA_ID_SEQ;

CREATE TABLE MEDIA (
	ID INT NOT NULL,
	IDAPLIKACIJE INT NOT NULL,
	IDLOKACIJE INT NOT NULL,
	HEADER VARCHAR2(255),
	SLIKA VARCHAR2(255),
	VIDEO VARCHAR2(255),
	FOOTER VARCHAR2(255),
	UPDATED TIMESTAMP,
	CREATED TIMESTAMP NOT NULL,
	IDUPDATED INT,
	IDCREATED INT NOT NULL,
	constraint MEDIA_PK PRIMARY KEY (ID))
/
CREATE sequence MEDIA_ID_SEQ;

CREATE trigger BI_MEDIA_ID
  before insert on MEDIA
  for each row
begin
  select MEDIA_ID_SEQ.nextval into :NEW.ID from dual;
end;
/
CREATE TRIGGER BI_MEDIA_CR 
BEFORE INSERT ON MEDIA 
for each row
BEGIN
    SELECT
        SYSTIMESTAMP
    INTO
        :NEW.CREATED
    FROM 
        DUAL;
END;
/
CREATE TRIGGER BU_MEDIA_UP 
BEFORE UPDATE ON MEDIA 
for each row
BEGIN
    SELECT
        SYSTIMESTAMP
    INTO
        :NEW.UPDATED
    FROM 
        DUAL;
END;

/
CREATE TABLE LOKACIJE (
	ID INT NOT NULL,
	LAT NUMBER(10,8) NOT NULL,
	LNG NUMBER(10,8) NOT NULL,
	TITLE VARCHAR2(4000) UNIQUE NOT NULL,
	TEKST VARCHAR2(4000) NOT NULL,
	MARKER VARCHAR2(255) NOT NULL,
	UPDATED TIMESTAMP,
	CREATED TIMESTAMP NOT NULL,
	IDCREATED INT NOT NULL,
	IDUPDATED INT,
	constraint LOKACIJE_PK PRIMARY KEY (ID));

CREATE sequence LOKACIJE_ID_SEQ;

CREATE trigger BI_LOKACIJE_ID
  before insert on LOKACIJE
  for each row
begin
  select LOKACIJE_ID_SEQ.nextval into :NEW.ID from dual;
end;
/
CREATE TRIGGER BI_LOKACIJE_CR 
BEFORE INSERT ON LOKACIJE 
for each row
BEGIN
    SELECT
        SYSTIMESTAMP
    INTO
        :NEW.CREATED
    FROM 
        DUAL;
END;
/
CREATE TRIGGER BU_LOKACIJE_UP 
BEFORE UPDATE ON LOKACIJE 
for each row
BEGIN
    SELECT
        SYSTIMESTAMP
    INTO
        :NEW.UPDATED
    FROM 
        DUAL;
END;

/
CREATE TABLE KORISNICI (
	ID INT NOT NULL,
	IME VARCHAR2(255) NOT NULL,
	PREZIME VARCHAR2(255) NOT NULL,
	EMAIL VARCHAR2(255) NOT NULL,
	PASSWORD VARCHAR2(255) NOT NULL,
	UPDATED TIMESTAMP,
	CREATED TIMESTAMP NOT NULL,
	constraint KORISNICI_PK PRIMARY KEY (ID));
/
CREATE sequence KORISNICI_ID_SEQ;

CREATE trigger BI_KORISNICI_ID
  before insert on KORISNICI
  for each row
begin
  select KORISNICI_ID_SEQ.nextval into :NEW.ID from dual;
end;
/
CREATE TRIGGER BI_KORISNICI_CR 
BEFORE INSERT ON KORISNICI 
for each row
BEGIN
    SELECT
        SYSTIMESTAMP
    INTO
        :NEW.CREATED
    FROM 
        DUAL;
END;
/
CREATE TRIGGER BU_KORISNICI_UP 
BEFORE UPDATE ON KORISNICI
for each row
BEGIN
    SELECT
        SYSTIMESTAMP
    INTO
        :NEW.UPDATED
    FROM 
        DUAL;
END;

/
CREATE TABLE APLIKACIJE (
	ID INT NOT NULL,
	IME VARCHAR2(255) UNIQUE NOT NULL,
	UPDATED TIMESTAMP,
	CREATED TIMESTAMP NOT NULL,
	IDUPDATED INT,
	IDCREATED INT NOT NULL,
	constraint APLIKACIJE_PK PRIMARY KEY (ID));
/
CREATE sequence APLIKACIJE_ID_SEQ;

CREATE trigger BI_APLIKACIJE_ID
  before insert on APLIKACIJE
  for each row
begin
  select APLIKACIJE_ID_SEQ.nextval into :NEW.ID from dual;
end;
/
CREATE TRIGGER BI_APLIKACIJE_CR 
BEFORE INSERT ON APLIKACIJE 
for each row
BEGIN
    SELECT
        SYSTIMESTAMP
    INTO
        :NEW.CREATED
    FROM 
        DUAL;
END;
/
CREATE TRIGGER BU_APLIKACIJE_UP 
BEFORE UPDATE ON APLIKACIJE 
for each row
BEGIN
    SELECT
        SYSTIMESTAMP
    INTO
        :NEW.UPDATED
    FROM 
        DUAL;
END;
/
ALTER TABLE MEDIA ADD CONSTRAINT MEDIA_fk0 FOREIGN KEY (IDAPLIKACIJE) REFERENCES APLIKACIJE(ID);
ALTER TABLE MEDIA ADD CONSTRAINT MEDIA_fk1 FOREIGN KEY (IDLOKACIJE) REFERENCES LOKACIJE(ID);
ALTER TABLE MEDIA ADD CONSTRAINT MEDIA_fk2 FOREIGN KEY (IDUPDATED) REFERENCES KORISNICI(ID);
ALTER TABLE MEDIA ADD CONSTRAINT MEDIA_fk3 FOREIGN KEY (IDCREATED) REFERENCES KORISNICI(ID);

ALTER TABLE LOKACIJE ADD CONSTRAINT LOKACIJE_fk0 FOREIGN KEY (IDCREATED) REFERENCES KORISNICI(ID);
ALTER TABLE LOKACIJE ADD CONSTRAINT LOKACIJE_fk1 FOREIGN KEY (IDUPDATED) REFERENCES KORISNICI(ID);

ALTER TABLE APLIKACIJE ADD CONSTRAINT APLIKACIJE_fk0 FOREIGN KEY (IDUPDATED) REFERENCES KORISNICI(ID);
ALTER TABLE APLIKACIJE ADD CONSTRAINT APLIKACIJE_fk1 FOREIGN KEY (IDCREATED) REFERENCES KORISNICI(ID);

